### ISSUE TITLE
Плагин sape 1.6 некорректно работает с PHP 7

### ISSUE THREAD

**Issue by andr55** [maxsite/plugins_for_maxsite_cms#1]
Пытаюсь перелезть с Maxsite CMS 0.77 на 104-ю. Сложности есть, но до этого удавалось решать. Сейчас проблема с плагином sape версии 1.6 на PHP 7.0 (старый Openserver c PHP 7.0.4).

С Maxsite CMS 104 и файлом sape.php версии 1.2.1 в тексте страниц показывается около 5-6 окошек типа: функция deprecated.

Когда меняю файл sape.php на последнюю версию (1.4.8), то нижняя половина страниц сайта перестает загружаться (с момента вывода первого блока sape).

В логах PHP-отладки Openserver вижу такое:

#0 C:\OpenServer\domains\mur\application\maxsite\plugins\sape\index.php(168): sape_widget_custom(Array, '2')
#1 C:\OpenServer\domains\mur\application\maxsite\common\common.php(2323): sape_widget('2')
#2 C:\OpenServer\domains\mur\application\maxsite\templates\max-sialia\main\main.php(32): mso_show_sidebar('1')
#3 C:\OpenServer\domains\mur\application\maxsite\shared\main\main-end.php(13): require('C:\\OpenServer\\d...')
#4 C:\OpenServer\domains\mur\application\maxsite\shared\type\page\page.php(313): require('C:\\OpenServer\\d...')
#5 C:\OpenServer\domains\mur\application\maxsite\templates\max-sialia\index.php(22): require('C:\\OpenServer\\d...')
#6 C:\OpenServer\domains\mur\application\views\index.php(12): require('C:\\OpenServer\\d...')
#7 C:\OpenServer\domains\mur\system\core\Loader.php(834): include('C:\\OpenServer\\d...')
#8 C:\OpenServer\domains\mur in C:\OpenServer\domains\mur\application\maxsite\plugins\sape\index.php on line 256

Что делать?

**Comment by andr55** [comment]
Написав вопрос, я заподозрил, что не вставил в мой шаблон первый блок показа ссылок sape. Нашел удобное место в шаблоне, вставил.

Ошибка плагина изменилась:

[24-Jan-2020 02:35:13 Europe/Moscow] PHP Fatal error:  Cannot access protected property SAPE_articles::$_data in C:\OpenServer\domains\mur\application\maxsite\plugins\sape\index.php on line 256

Что еще можно сделать?

**Comment by andr55** [comment]
Ради интереса в настройках плагина sape снял галочку "Включить публикацию статей". Ошибка в логах стала такой:

[24-Jan-2020 12:16:01 Europe/Moscow] PHP Fatal error:  Call to a member function return_announcements() on boolean in C:\OpenServer\domains\mur\application\maxsite\plugins\sape\index.php on line 253
